import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import ThemeState from '@/context/ThemeState'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shinobi | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeState>
          <Navbar />
          {children}
        </ThemeState>
      </body>
    </html>
  )
}
